services:
  # 1. Kafka (KRaft Mode)
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft 설정
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # 리스너 설정: 내부 통신용(29092)과 외부 접속용(9092)을 분리
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_INTERNAL://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      # 기타 필수 설정
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka-network

  # 2. Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8989:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      # UI는 컨테이너 내부 네트워크인 29092 포트로 접속합니다.
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    networks:
      - kafka-network

  # 3. Redis
  redis:
    image: redis:alpine
    container_name: billgates-redis
    ports:
      - "6379:6379"
    # 메모리 데이터를 60초마다 디스크에 저장(안전장치) & 로그 레벨 조정
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - kafka-network

  # 4. Mailpit (이메일 테스트용)
  mailpit:
    image: axllent/mailpit:latest
    container_name: billgates-mailpit
    ports:
      - "1025:1025"  # SMTP 포트
      - "8025:8025"  # Web UI 포트
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
    networks:
      - kafka-network


volumes:
  kafka-data:

networks:
  kafka-network:
    driver: bridge