spring.application.name=BillGates

# Import .env file
spring.config.import=optional:file:.env[.properties]

# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate -> jpa ?? ??
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG

#thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

#jpa table -> jpa ?? ??
#jpa? db ??? ?? ??
#spring.jpa.hibernate.ddl-auto=none

#spring batch
spring.batch.jdbc.initialize-schema=never


#server-tomcat
server.tomcat.mbeanregistry.enabled=true