spring.application.name=BillGates

# Import .env file
spring.config.import=optional:file:.env[.properties]

# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# data.sql ?? ?? (item ??? ???)
spring.sql.init.mode=never
spring.sql.init.encoding=UTF-8
spring.sql.init.data-locations=classpath:data.sql

# Hibernate -> jpa ?? ??
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG

#thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

#jpa table -> jpa ?? ??
#jpa? db ??? ?? ??
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring batch
spring.batch.jdbc.initialize-schema=never
spring.batch.job.enabled=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
# ???? ?? ??? Entity? ?? ??? ?? ???? ??
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#server-tomcat
server.tomcat.mbeanregistry.enabled=true

#kafka
spring.kafka.consumer.properties.spring.json.value.default.type=springboot.billgates.kafka.dto.NotificationEvent
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# Batch ??
spring.kafka.producer.properties.batch.size=16384
# 16KB ?? ?? ??

# Linger (?? ??)
spring.kafka.producer.properties.linger.ms=10
# ?? ? ?? 10ms ? ??

# ??
spring.kafka.producer.properties.compression.type=snappy
# ???? ??? ??

# ?? ???
spring.kafka.producer.properties.buffer.memory=33554432
# 32MB

# ??? ??
spring.kafka.producer.properties.enable.idempotence=true
# ?? ??

# Acks
spring.kafka.producer.acks=1
# Leader? ??

# ????
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.delivery.timeout.ms=120000


spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Consumer ??? (12 Partitions)
spring.kafka.listener.concurrency=12

# encrypt util
encryption.secret=${ENCRYPTION_SECRET}
encryption.iv=${ENCRYPTION_IV}

#DB
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false